name: Test CI-CD
run-name: commit ${{ github.sha }} of branch ${{ github.ref}} by @${{ github.actor }}

on: 
  push:
    branches:
      - master
      - develop

permissions:
  contents: write

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Compile, Unit Test and Install
        id: unit-tests
        run: mvn clean install

      - name: Build with Maven
        run: mvn -B package --file pom.xml
